import type { Product } from '@/lib/types';

// Données de démo — remplacées par Supabase dès le pipeline actif
export const DEMO_PRODUCTS: Partial<Product>[] = [
  {
    id: '1',
    slug: 'huile-essentielle-lavande-bleue',
    nameFr: 'Huile essentielle Lavande bleue',
    descriptionFr: "Huile essentielle 100% pure et naturelle de lavande bleue (Lavandula angustifolia). Reconnue pour ses vertus apaisantes, elle favorise la relaxation et un sommeil réparateur. Idéale en diffusion ou diluée dans une huile végétale pour un massage apaisant.",
    category: 'aromatherapie',
    retailPriceEur: 18,
    compareAtPriceEur: 24,
    stockStatus: 'Normal',
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['lavande', 'huile-essentielle', 'sommeil', 'relaxation'],
    images: ['/images/udz-cat-aromatherapie.jpeg'],
  },
  {
    id: '2',
    slug: 'bougie-soja-vanille',
    nameFr: 'Bougie de soja Vanille & Bois de Santal',
    descriptionFr: "Bougie artisanale en cire de soja pure, parfumée à la vanille douce et au bois de santal. Durée de combustion : 40 heures. Fabriquée à la main, sans paraffine, sans OGM. La mèche en coton offre une flamme stable et sans fumée.",
    category: 'bougies',
    retailPriceEur: 22,
    stockStatus: 'Normal',
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['bougie', 'soja', 'vanille', 'santal'],
    images: ['/images/udz-cat-bougies.jpeg'],
  },
  {
    id: '3',
    slug: 'palo-santo-lot-6',
    nameFr: 'Palo Santo sacré (lot de 6 bâtons)',
    descriptionFr: "Le Palo Santo (« bois sacré ») est utilisé depuis des siècles en Amérique du Sud pour purifier l'énergie des espaces et favoriser la méditation. Lot de 6 bâtons sélectionnés à la main, séchés naturellement sans abattage d'arbres vivants.",
    category: 'encens',
    retailPriceEur: 14,
    stockStatus: 'Low',
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['palo-santo', 'encens', 'purification', 'meditation'],
    images: ['/images/udz-cat-encens.jpeg'],
  },
  {
    id: '4',
    slug: 'quartz-rose-brut',
    nameFr: 'Quartz rose brut — Pierre de la douceur',
    descriptionFr: "Quartz rose brut de qualité supérieure, sélectionné pour sa couleur et son énergie. Pierre associée à l'amour inconditionnel et à la sérénité intérieure. Idéal en décoration ou en pratique lithothérapique. Dimensions : 5–7 cm environ.",
    category: 'pierres-cristaux',
    retailPriceEur: 12,
    stockStatus: 'Normal',
    isVegan: true,
    isCrueltyFree: true,
    tags: ['quartz', 'rose', 'pierre', 'cristal'],
    images: ['/images/udz-cat-cristaux.jpeg'],
  },
  {
    id: '5',
    slug: 'bougie-meditation-bois-cedre',
    nameFr: 'Bougie Méditation — Cèdre & Vétiver',
    descriptionFr: "Une fragrance boisée et enracinante pour accompagner vos séances de méditation ou de yoga. Cire de soja, cèdre de l'Atlas, vétiver de Madagascar. Contenant en verre réutilisable.",
    category: 'bougies',
    retailPriceEur: 26,
    stockStatus: 'Normal',
    isBestSeller: false,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['bougie', 'meditation', 'cedre', 'vetiver'],
    images: ['/images/udz-cat-bougies.jpeg'],
  },
  {
    id: '6',
    slug: 'set-encens-nag-champa',
    nameFr: 'Set Encens Nag Champa — 40 bâtonnets',
    descriptionFr: "Nag Champa, le parfum emblématique de l'Inde. Ces bâtonnets artisanaux au mélange de fleur de frangipanier et de résines naturelles créent une atmosphère de paix profonde. Confectionnés sans charbon, combustion lente (45 min par bâtonnet).",
    category: 'encens',
    retailPriceEur: 9,
    compareAtPriceEur: 12,
    stockStatus: 'Normal',
    isVegan: true,
    isCrueltyFree: true,
    tags: ['encens', 'nag-champa', 'inde', 'meditation'],
    images: ['/images/udz-cat-encens.jpeg'],
  },
  {
    id: '7',
    slug: 'diffuseur-ultra-sonic-bambou',
    nameFr: "Diffuseur ultrasonique — Design Bambou",
    descriptionFr: "Diffuseur ultrasonique en bois de bambou et céramique blanche. Silencieux, couvre jusqu'à 30 m². 7 couleurs LED, minuterie 1h/3h/6h. Idéal pour diffuser vos huiles essentielles et créer une ambiance zen dans toute la maison.",
    category: 'aromatherapie',
    retailPriceEur: 44,
    stockStatus: 'Normal',
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['diffuseur', 'ultrasonique', 'bambou', 'aromatherapie'],
    images: ['/images/udz-cat-aromatherapie.jpeg'],
  },
  {
    id: '8',
    slug: 'the-matcha-ceremonie-japon',
    nameFr: 'Matcha Cérémonie — Japon Uji',
    descriptionFr: "Matcha de grade cérémonie issu des jardins d'Uji, Kyoto. Récolte de printemps, premier flush. Couleur vert intense, saveur douce et umami. 30g en boîte hermétique protégée de la lumière.",
    category: 'thes-artisanaux',
    retailPriceEur: 19,
    stockStatus: 'Low',
    isBestSeller: false,
    isVegan: true,
    isCrueltyFree: true,
    isOrganic: true,
    tags: ['matcha', 'the', 'japon', 'ceremonie'],
    images: ['/images/udz-cat-thes.jpeg'],
  },
];

export const CATEGORIES = [
  { slug: 'aromatherapie', label: 'Aromathérapie' },
  { slug: 'bougies', label: 'Bougies' },
  { slug: 'encens', label: 'Encens' },
  { slug: 'pierres-cristaux', label: 'Pierres & Cristaux' },
  { slug: 'maison-deco', label: 'Maison & Déco' },
  { slug: 'thes-artisanaux', label: 'Thés Artisanaux' },
];
