import type { Product } from '@/lib/types';

export interface DemoProduct extends Partial<Product> {
  shortDescriptionFr: string;
  longDescriptionFr: string;
  benefitsFr: string[];
  usageFr: string;
  faqFr: { question: string; answer: string }[];
  characteristics: { label: string; value: string }[];
}

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    id: '1',
    slug: 'huile-essentielle-lavande-bleue',
    nameFr: 'Huile essentielle Lavande bleue — 10 ml',
    shortDescriptionFr: "Pure et naturelle, notre huile de lavande vraie favorise la détente et un sommeil réparateur.",
    descriptionFr: "Distillée à la vapeur d’eau depuis les champs de lavande provenaux, cette huile essentielle de lavande vraie (Lavandula angustifolia) est la référence bien-être par excellence. D’une pureté irréprochable, elle est récoltée à la main à l’altitude idéale (800–1400 m) pour une concentration maximale en linélool et linélyl acétate.",
    longDescriptionFr: "La lavande vraie est l’huile essentielle la plus étudiée et la plus polyvale de l’aromathérapie moderne. Ses propriétés calmantes, anti-inflammatoires et cicatrisantes en font un in dispensable de toute pharmacie familiale naturelle.\n\nEn diffusion atmosphérique, elle transforme n’importe quelle pièce en havre de paix. En application topique — diluée à 2% dans une huile végétale comme le jojoba — elle soulage les tensions musculaires, apaise les petites brûlures et accélère la guérison des petites plaies.\n\nNos bouteilles en verre foncé amber protgènt les molécules actives de la dégradation lumière. Chaque lot est testé par chromatographie gaz (GC-MS) pour garantir la composition aromatique attendue.",
    benefitsFr: [
      "Favorise l’endormissement et améliore la qualité du sommeil",
      "Réduit le stress et l’anxieté au quotidien",
      "Apaise les petites irritations et brûlures cutanes",
      "100% pure, sans synthétique ni additif",
    ],
    usageFr: "Diffusion : 4–6 gouttes dans votre diffuseur ultrasonique, 30 minutes. Application : diluée à 2% dans l’huile végétale de votre choix (jojoba, amande douce). Bain : 5 gouttes préalablement mélangées dans une cuillère à soupe de sel de bain. Déconseillée pure sur peau sensible.",
    faqFr: [
      { question: "Peut-on utiliser cette huile pendant la grossesse ?", answer: "Déconseillée durant le 1er trimestre. À utiliser uniquement en diffusion atmosphérique à partir du 2e trimestre, et avec l’avis de votre médecin." },
      { question: "Est-elle adaptable aux enfants ?", answer: "Oui, la lavande vraie est l’une des rares huiles utilisables chez les enfants dès 3 ans, en diffusion ou très diluée (0.5%) en massage. Déconseillée chez les nourrissons." },
      { question: "Quelle est la durée de conservation ?", answer: "4 à 5 ans si stockée à l’abri de la lumière et de la chaleur, flacon bien fermé." },
    ],
    characteristics: [
      { label: 'Nom botanique', value: 'Lavandula angustifolia' },
      { label: 'Origine', value: 'France (Provence)' },
      { label: 'Partie utilisée', value: 'Sommités fleuries' },
      { label: 'Extraction', value: 'Distillation vapeur' },
      { label: 'Volume', value: '10 ml' },
      { label: 'Conservation', value: '4–5 ans' },
    ],
    category: 'aromatherapie',
    retailPriceEur: 18,
    compareAtPriceEur: 24,
    stockStatus: 'Normal',
    stockQty: 47,
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['lavande', 'huile-essentielle', 'sommeil', 'relaxation'],
    images: ['/images/udz-cat-aromatherapie.jpeg'],
  },
  {
    id: '2',
    slug: 'bougie-soja-vanille-santal',
    nameFr: 'Bougie de soja Vanille & Bois de Santal',
    shortDescriptionFr: "Cire de soja pure, mèche en coton, parfum vanille-santal. 45h de combustion propre.",
    descriptionFr: "Fabriquée à la main par nos artisans partenaires, cette bougie allie la douceur vanillée à la chaleur boisée du santal blanc de Mysore. La cire de soja 100% végétale assure une combustion lente, sans suie ni toxines.",
    longDescriptionFr: "La vanille et le bois de santal forment l’un des accords aromatiques les plus intemporels du parfum. Ensemble, ils créent une chaleur sensuelle, enveloppante, qui rappelle les soirées d’automne et les intérieurs douillets.\n\nNotre cire de soja provient de soja non-OGM certifié. Elle brûle à une température 20% inférieure à la paraffine, ce qui signifie une libération plus progressive du parfum et une durée de vie plus longue (45h vs 30h pour une bougie paraffine équivalente).\n\nLe contenant en verre soufflé ambré peut être réutilisé une fois la bougie consommée : nettoyez-le à l’eau chaude pour obtenir un pot idéal pour vos cotons-tiges, boucles d’oreilles ou plantes succulentes.",
    benefitsFr: [
      "Cire de soja végétale — zéro suie, zéro toxine",
      "45 heures de combustion économique",
      "Parfum naturel longuement diffusé",
      "Contenant en verre réutilisable",
    ],
    usageFr: "Coupez la mèche à 5 mm avant chaque allumage. Lors de la 1ère utilisation, laissez brider au moins 2h (jusqu’à ce que le fond de cire soit entièrement fondu) pour éviter l’effet tunnel. Ne jamais brûler plus de 4h d’affilée. Tenir éloigné des enfants et animaux.",
    faqFr: [
      { question: "Le parfum est-il synthétique ou naturel ?", answer: "Notre accord vanille-santal utilise une base de parfum de synthèse de haute qualité, sans phtalates ni CMR. Nous privilégions les compositions certifiées IFRA et toutes nos bougies sont testales dérmatologiquement." },
      { question: "La bougie est-elle livrée dans une boîte ?", answer: "Oui, dans une boîte carton recyclé personnalisée. Idéale pour offrir, directement emballée." },
      { question: "Puis-je utiliser le contenant après ?", answer: "Absolument ! Attendez que la cire restante soit solide, placez au congélateur 30 minutes, puis retirez le reste de cire avec une spatule. Lavez au lave-vaisselle." },
    ],
    characteristics: [
      { label: 'Cire', value: 'Soja 100% végétal' },
      { label: 'Mèche', value: 'Coton naturel tressé' },
      { label: 'Poids net', value: '200g' },
      { label: 'Durée combustion', value: '45 heures' },
      { label: 'Contenant', value: 'Verre ambré réutilisable' },
      { label: 'Dimensions', value: 'Ø8.5 cm × H9 cm' },
    ],
    category: 'bougies',
    retailPriceEur: 22,
    stockStatus: 'Normal',
    stockQty: 31,
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['bougie', 'soja', 'vanille', 'santal'],
    images: ['/images/udz-cat-bougies.jpeg'],
  },
  {
    id: '3',
    slug: 'palo-santo-lot-6-batons',
    nameFr: 'Palo Santo sacré — Lot de 6 bâtons',
    shortDescriptionFr: "Bois sacré d’Amérique du Sud, récolté sur bois tombés naturellement. Purifie l’espace et favorise la méditation.",
    descriptionFr: "Le Palo Santo (Bursera graveolens) est un bois sacré utilisé depuis des siècles par les chamans d’Amérique latine pour purifier les espaces et ancrer la méditation. Notre Palo Santo provient éxclusivement de bois tombés naturellement au Pérou.",
    longDescriptionFr: "Le terme « Palo Santo » signifie littéralement « bois saint » en espagnol. Les Incas l’utilisaient dans leurs cérémonies spirituelles pour chasser les mauvaises énergies et invoquer la protection divine. Aujourd’hui, il s’est imposé dans le monde du bien-être comme une alternative écologique et parfumée à la sauge blanche.\n\nSon parfum est unique : des notes de citron et de menthe sur un fond de bois résineux doux. Brûlé, il dégage une fumée fine et parfumée qui se dissipe rapidement, laissant derrière elle une atmosphère de calme et de légèreté.\n\nNotre Palo Santo est récolté sur des arbres tombés naturellement après un minimum de 4 ans de séchage naturel — le temps nécessaire pour que les huiles aromatiques se concentrent dans le bois mort. Certifié commerce équitable.",
    benefitsFr: [
      "Purifie et éclaircit l’énergie de l’espace",
      "Favorise la concentration et la méditation",
      "Récolte durable — bois tombés naturellement",
      "Parfum boisé citronné unique et apaisant",
    ],
    usageFr: "Allumez l’extrémité du bâton, laissez flamber 30 secondes puis soufflez pour éteindre. Promencez la fumée dans la pièce en gardant une intention positive. Le bâton s’éteint naturellement. Chaque bâton peut être utilisé plusieurs fois.",
    faqFr: [
      { question: "Combien de fois peut-on utiliser un bâton ?", answer: "5 à 10 utilisations selon la taille et la durée de chaque séance. Le bâton s’éteint naturellement quand vous cessez de souffler dessus." },
      { question: "Peut-on l’utiliser dans une pièce sans fenêtre ?", answer: "Déconsillé. Ventilez toujours l’espace pendant et après l’utilisation, même si la fumée de Palo Santo est très légère." },
      { question: "Votre Palo Santo est-il écologique ?", answer: "Oui. Nous ne vendons que du Palo Santo issu de bois tombés naturellement et séchés au minimum 4 ans. Aucun abattage d’arbre vivant." },
    ],
    characteristics: [
      { label: 'Espèce', value: 'Bursera graveolens' },
      { label: 'Origine', value: 'Pérou' },
      { label: 'Lot', value: '6 bâtons' },
      { label: 'Longueur', value: '10 cm environ' },
      { label: 'Poids total', value: '60g environ' },
      { label: 'Certification', value: 'Commerce équitable' },
    ],
    category: 'encens',
    retailPriceEur: 14,
    stockStatus: 'Low',
    stockQty: 6,
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['palo-santo', 'encens', 'purification', 'meditation'],
    images: ['/images/udz-cat-encens.jpeg'],
  },
  {
    id: '4',
    slug: 'quartz-rose-brut-pierre-douceur',
    nameFr: 'Quartz rose brut — Pierre de la douceur',
    shortDescriptionFr: "Quartz rose naturel de qualité supérieure, associé à l’amour inconditionnel et à la sérénité intérieure.",
    descriptionFr: "Notre quartz rose brut est sélectionné pour sa couleur rosée intense et sa transparence. Chaque pièce est unique, taille 5–7 cm. Pierre associée à l’amour, la compassion et la détente émotionnelle.",
    longDescriptionFr: "Le quartz rose est la pierre de l’amour inconditionnel — amour de soi, amour des autres, amour de la vie. Sa teinte rosée douce, due à la présence de titâne et de manganèse, en fait l’un des cristâux les plus estimés de la lithérapie.\n\nNos quartz roses proviennent des mines éthiques de Madagascar et du Brésil, où ils sont extraits à la main pour préserver leur intégrité cristalline. Chaque pièce est unique : la forme brute préserve l’énergie naturelle de la pierre sans intervention humaine excessive.\n\nEn décoration, il apporte une énergie de douceur et de sereénité dans n’importe quelle pièce. Posé sur votre bureau, votre table de chevet ou dans votre espace de méditation, il rappelle l’invitation à la bienveillance envers soi-même et les autres.",
    benefitsFr: [
      "Encourage l’amour de soi et la bienveillance",
      "Adoucit les émotions et réduit le stress",
      "Pierre brute — énergie non altrée",
      "Idéale en déco ou en lithérapie",
    ],
    usageFr: "Tenez la pierre dans votre main dominante lors de vos séances de méditation. Placez-la sous votre oreiller pour favoriser des rêves positifs. Purifiez-la régulièrement au Palo Santo, à l’eau claire ou à la lumière de la pleine lune.",
    faqFr: [
      { question: "Quelle est la taille exacte de la pierre ?", answer: "Chaque pièce est unique, entre 5 et 7 cm dans sa plus grande dimension. Poids : 80–150g environ. La photo est représentative de la qualité mais non de la taille exacte." },
      { question: "Est-elle livrée avec des informations sur ses propriétés ?", answer: "Oui, chaque pierre est livrée dans une pochette en lin avec une carte explicative des propriétés traditionnelles et des conseils de purification." },
      { question: "La pierre est-elle 100% naturelle ?", answer: "Oui, entièrement naturelle. Sans traitement, sans teinture, sans irradiation. La couleur rose est 100% naturelle." },
    ],
    characteristics: [
      { label: 'Minéral', value: 'Quartz rose (SiO₂)' },
      { label: 'Origine', value: 'Madagascar / Brésil' },
      { label: 'Format', value: 'Brut naturel' },
      { label: 'Taille', value: '5–7 cm' },
      { label: 'Poids', value: '80–150g' },
      { label: 'Livraison', value: 'Pochette en lin incluse' },
    ],
    category: 'pierres-cristaux',
    retailPriceEur: 12,
    stockStatus: 'Normal',
    stockQty: 23,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['quartz', 'rose', 'pierre', 'cristal'],
    images: ['/images/udz-cat-cristaux.jpeg'],
  },
  {
    id: '5',
    slug: 'diffuseur-ultrasonique-bambou',
    nameFr: 'Diffuseur ultrasonique — Design Bambou & Céramique',
    shortDescriptionFr: "Diffuseur silencieux en bambou naturel et céramique blanche. Couvre 30m², 7 LED, minuterie 1h/3h/6h.",
    descriptionFr: "Ce diffuseur ultrasonique alliance le design scandinave au matériau bambou. Sa technologie à vibrations ultrasoniques (pas de chaleur) préserve à 100% les molécules actives des huiles essentielles.",
    longDescriptionFr: "Le diffuseur ultrasonique est l’outil idéal pour profiter de tous les bienfaits de l’aromathérapie à la maison ou au bureau. Contrairement aux diffuseurs à chaleur qui dénaturent les molécules actives, la technologie ultrasonique crée une micro-brume froide qui préserve intégralement les propriétés thérapeutiques des huiles.\n\nLe bambou utilisé pour le corps du diffuseur est certifié FSC, récolté de manière durable. La céramique blanche est fabriquée artisanalement au Portugal. L’ensemble dégage une élégance naturelle qui s’intègre à tous les intérieurs.\n\nAvec son réservoir de 300ml, il fonctionne jusqu’à 8 heures en mode continu. La fonction arret automatique quand le niveau d’eau est bas évite tout dommage. Les 7 couleurs LED peuvent être désactivées pour une utilisation nocturne discrète.",
    benefitsFr: [
      "Technologie froide — préserve les molécules actives",
      "Silencieux : < 30 dB, parfait pour la chambre",
      "Bambou certifié FSC et céramique artisanale",
      "Arrêt automatique sécurisé quand vide",
    ],
    usageFr: "Remplissez le réservoir avec de l’eau à température ambiante (pas distillée). Ajoutez 5–8 gouttes d’huile essentielle. Sélectionnez la durée (1h, 3h, 6h ou continu) et la couleur LED souhaitée. Nettoyez le réservoir une fois par semaine avec un coton-tige imbibé d’alcool.",
    faqFr: [
      { question: "Quelle quantité d’huile essentielle utiliser ?", answer: "Généralement 5–8 gouttes pour 300ml d’eau. Commencez par 5 gouttes et adaptez selon l’intensité souhaitée et la surface de la pièce." },
      { question: "Quelle surface couvre-t-il ?", answer: "Optimal jusqu’à 30m². Pour de grandes pièces open-space (> 40m²), nous recommandons deux diffuseurs en opposition." },
      { question: "Le cable d’alimentation est-il inclus ?", answer: "Oui, câble USB inclus (adaptateur secteur non fourni). Compatible avec les chargeurs USB standard 5V/1A." },
    ],
    characteristics: [
      { label: 'Matériau', value: 'Bambou FSC + Céramique' },
      { label: 'Capacité', value: '300 ml' },
      { label: 'Surface', value: 'Jusqu’à 30 m²' },
      { label: 'Autonomie', value: '8h en continu' },
      { label: 'Niveau sonore', value: '< 30 dB' },
      { label: 'Alimentation', value: 'USB 5V / 1A' },
    ],
    category: 'aromatherapie',
    retailPriceEur: 44,
    stockStatus: 'Normal',
    stockQty: 18,
    isBestSeller: true,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['diffuseur', 'ultrasonique', 'bambou', 'aromatherapie'],
    images: ['/images/udz-cat-aromatherapie.jpeg'],
  },
  {
    id: '6',
    slug: 'encens-nag-champa-40-batonnets',
    nameFr: 'Encens Nag Champa artisanal — 40 bâtonnets',
    shortDescriptionFr: "Le parfum emblématique de l’Inde, confectionné à la main. Combustion lente 45 min, sans charbon.",
    descriptionFr: "Nag Champa est le parfum de l’Inde éternelle. Ces bâtonnets artisanaux à base de fleur de frangipanier, santal et résines naturelles sont confectionnés selon la recette traditionnelle, sans charbon de bois.",
    longDescriptionFr: "Le Nag Champa tient son nom de la fleur Champaka (Michelia champaca) et du nagakesar, une flèur sacrée. Sa composition exacte varie selon les maîtres parfumeurs, mais le cœur reste invariable : santal, fleur de champaka, résines naturelles et huiles aromatiques.\n\nNos bâtonnets sont produits à Bangalore par des artisans qui transmettent leur savoir-faire depuis 4 générations. La fabrication à la main garantit une combustion régulière et une diffusion homogène du parfum. Chaque bâtonnet brule environ 45 minutes, soit près de 30h au total pour la boite de 40.\n\nSans charbon de bois, ces encens libèrent une fumée plus fine et moins âcre que les encens à base de charbon. Ils sont idéaux pour la méditation, le yoga ou simplement pour parfumer une pièce de manière authentique.",
    benefitsFr: [
      "Recette traditionnelle indienne — fabrication main",
      "Sans charbon — fumée fine et pure",
      "45 min de combustion par bâtonnet",
      "Parfum authentique floral-boisé",
    ],
    usageFr: "Insérez le bâtonnet dans un porte-encens adapté. Allumez l’extrémité, attendez une flamme franche (10s), puis éteignez en soufflant. La braise se maintient et diffuse le parfum. Utilisez dans une pièce aérée.",
    faqFr: [
      { question: "Faut-il un porte-encens spécial ?", answer: "N’importe quel porte-encens à bâtonnets convient. Nous proposons des porte-encens bambou et céramique dans notre rayon Maison & Déco." },
      { question: "Ces encens conviennent-ils aux enfants ?", answer: "Déconseillé en présence de nourrissons et très jeunes enfants. Ventilez toujours la pièce pendant l’utilisation." },
      { question: "Y a-t-il du gluten dans ces encens ?", answer: "Non, nos encens Nag Champa sont sans gluten et végans." },
    ],
    characteristics: [
      { label: 'Parfum', value: 'Nag Champa (floral-boisé)' },
      { label: 'Composition', value: 'Frangipanier, santal, résines' },
      { label: 'Contenu', value: '40 bâtonnets' },
      { label: 'Combustion', value: '45 min / bâtonnet' },
      { label: 'Origine', value: 'Bangalore, Inde' },
      { label: 'Sans charbon', value: 'Oui' },
    ],
    category: 'encens',
    retailPriceEur: 9,
    compareAtPriceEur: 12,
    stockStatus: 'Normal',
    stockQty: 55,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['encens', 'nag-champa', 'inde', 'meditation'],
    images: ['/images/udz-cat-encens.jpeg'],
  },
  {
    id: '7',
    slug: 'matcha-ceremonie-japon-uji',
    nameFr: 'Matcha de Cérémonie — Uji, Japon (30g)',
    shortDescriptionFr: "Premier flush de printemps, jardin d’Uji (Kyoto). Vert intense, saveur douce et umami. Grade cérémonie.",
    descriptionFr: "Notre matcha de grade cérémonie provient des jardins centenaires d’Uji, à Kyoto. Récolté lors du premier flush de printemps, ombragé 6 semaines, broyaé sur meule de pierre. L-théanine maximale, amerétume nulle.",
    longDescriptionFr: "Uji, à quelques kilomètres de Kyoto, est considéré comme le berceau du matcha de qualité supérieure. Les jardins y sont cultivés depuis le XIIe siècle, selon des techniques transmises de génération en génération.\n\nLa clé de la qualité d’un matcha tient dans l’ombraison : 4 à 6 semaines avant la récolte, les plants sont couverts pour bloquer la lumière directe. Cela force la plante à produire plus de chlorophylle (couleur vert intense) et de L-théanine (acide aminé responsable de la douceur et des effets relaxants). Résultat : une saveur douce, umami, aux amérs négligeables.\n\nNotre matcha est broyaé sur meule de granit à basse vitesse pour éviter l’échauffement et conserver toutes les propriétés antioxydantes des catéchines (EGCG). Il est livré dans une boîte hermétique et opaque qui le protège de la lumière et de l’air.",
    benefitsFr: [
      "Riche en L-théanine — énergie calm et concentrée",
      "Antioxydants EGCG × 137 versus thé vert classique",
      "Grade cérémonie — amerétume nulle",
      "Bio certifié — zéro pesticide",
    ],
    usageFr: "Tamisez 1–2g de matcha dans un bol. Ajoutez 70ml d’eau à 70°C (jamais bouillante). Fouettez vigoureusement en mouvement en W avec un fouet bambou (chasen) jusqu’à obtenir une mousse homogène. Consommez immédiatement.",
    faqFr: [
      { question: "Puis-je l’utiliser pour des lattes ou pâtisseries ?", answer: "Ce grade cérémonie est optimal en thé nature. Pour les lattes et recettes, un grade culinaire (moins cher) est plus adapté. Nous proposons également du matcha culinaire dans notre catalogue." },
      { question: "Contient-il de la cafféine ?", answer: "Oui — environ 35mg par portion (2g), libérée progressivement grâce à la L-théanine. Effet énergie douce et stable, sans pic ni crash." },
      { question: "Comment le conserver après ouverture ?", answer: "Refermez hermétiquement et conservez au réfrigérateur (5-10°C) après ouverture. Consommez dans les 4 semaines pour un goût optimal." },
    ],
    characteristics: [
      { label: 'Grade', value: 'Cérémonie (premium)' },
      { label: 'Origine', value: 'Uji, Kyoto, Japon' },
      { label: 'Récolte', value: 'Premier flush printemps 2026' },
      { label: 'Ombraison', value: '6 semaines' },
      { label: 'Broyage', value: 'Meule de granit lente' },
      { label: 'Poids net', value: '30g' },
      { label: 'Certification', value: 'Agriculture biologique JAS' },
    ],
    category: 'thes-artisanaux',
    retailPriceEur: 19,
    stockStatus: 'Low',
    stockQty: 8,
    isBestSeller: false,
    isVegan: true,
    isCrueltyFree: true,
    isOrganic: true,
    tags: ['matcha', 'the', 'japon', 'ceremonie'],
    images: ['/images/udz-cat-thes.jpeg'],
  },
  {
    id: '8',
    slug: 'bougie-meditation-cedre-vetiver',
    nameFr: 'Bougie Méditation — Cèdre & Vétiver',
    shortDescriptionFr: "Fragrance boisée et enracinante pour vos séances de méditation. Cèdre Atlas, vétiver de Madagascar, cire de soja.",
    descriptionFr: "Conçue spécifiquement pour accompagner la méditation et le yoga, cette bougie associe le cèdre de l’Atlas (ancrage, protection) au vétiver de Madagascar (enracinement, paix intérieure). Contenant en verre transparent réutilisable.",
    longDescriptionFr: "Les parfums boisés terreux ont une action remarquable sur le système nerveux : ils stimulent les récepteurs olfactifs liés au sentiment de sécurité et d’enracinement. Le cèdre de l’Atlas, utilisé en médecine ayurvédique depuis des siècles, est reconnu pour ses propriétés calmantes et ancrées. Le vétiver, appelé « l’huile de la tranquillité », est l’un des meilleurs allis contre le stress mental et l’hyperstimulation.\n\nCette bougie a été formulée par notre perfumeur partenaire spécialiste des aromes thérapeutiques. La concentration en huiles essentielles est volontairement équilibrée pour une diffusion progressive sur toute la durée de combustion (40h).\n\nLe contenant en verre transparent laisse voir le jeu de la flamme à travers la cire dorée — un spectacle en soi, pendant votre méditation.",
    benefitsFr: [
      "Favorise l’ancrage et la concentration",
      "Formulé par un parfumeur spécialiste bien-être",
      "40 heures de combustion lente et homogène",
      "Parfum à base d’huiles essentielles pures",
    ],
    usageFr: "Allumez 10–15 minutes avant le début de votre séance de méditation pour que le parfum ait le temps de se diffuser. Placez à bonne distance de votre natte (laisser circuler l’air). Éteignez doucement avec un éteignoir à bougie pour éviter la fumée.",
    faqFr: [
      { question: "Cette bougie contient-elle des huiles essentielles pures ?", answer: "Oui, le cèdre Atlas et le vétiver utilissés sont des huiles essentielles pures, complétées par un accord boisé naturel. Concentration totale 8% en matères aromatiques." },
      { question: "Convient-elle aux personnes asthmatiques ?", answer: "Par précaution, déconseillée aux personnes souffrant d’asthme ou d’allergies respiratoires sans avis médical. Veillez à aérer la pièce." },
      { question: "Y a-t-il une différence entre cette bougie et une bougie parfumée classique ?", answer: "La concentration en matières aromatiques (8%) est supérieure aux bougies de grande distribution (3-4%). Les parfums sont sélectionnés pour leurs propriétés psycho-aromatiques, pas seulement pour l’agrément." },
    ],
    characteristics: [
      { label: 'Parfum principal', value: 'Cèdre Atlas + Vétiver' },
      { label: 'Cire', value: 'Soja 100% végétal' },
      { label: 'Poids net', value: '180g' },
      { label: 'Combustion', value: '40 heures' },
      { label: 'Contenant', value: 'Verre transparent réutilisable' },
      { label: 'Matères aromatiques', value: '8%' },
    ],
    category: 'bougies',
    retailPriceEur: 26,
    stockStatus: 'Normal',
    stockQty: 14,
    isVegan: true,
    isCrueltyFree: true,
    tags: ['bougie', 'meditation', 'cedre', 'vetiver'],
    images: ['/images/udz-cat-bougies.jpeg'],
  },
];

export const CATEGORIES = [
  { slug: 'aromatherapie', label: 'Aromathérapie' },
  { slug: 'bougies', label: 'Bougies' },
  { slug: 'encens', label: 'Encens' },
  { slug: 'pierres-cristaux', label: 'Pierres & Cristaux' },
  { slug: 'maison-deco', label: 'Maison & Déco' },
  { slug: 'thes-artisanaux', label: 'Thés Artisanaux' },
];
